// <auto-generated />
using MaxiSchool.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaxiSchool.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20240606075824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MatiereProfesseur", b =>
                {
                    b.Property<int>("MatieresMatiereId")
                        .HasColumnType("int");

                    b.Property<int>("ProfesseursProfesseurId")
                        .HasColumnType("int");

                    b.HasKey("MatieresMatiereId", "ProfesseursProfesseurId");

                    b.HasIndex("ProfesseursProfesseurId");

                    b.ToTable("MatiereProfesseur");
                });

            modelBuilder.Entity("MaxiSchool.Models.Classe", b =>
                {
                    b.Property<int>("ClasseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClasseId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ClasseId");

                    b.ToTable("Classes", (string)null);
                });

            modelBuilder.Entity("MaxiSchool.Models.Eleve", b =>
                {
                    b.Property<int>("EleveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EleveId"));

                    b.Property<int>("ClasseId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EleveId");

                    b.HasIndex("ClasseId");

                    b.ToTable("Eleves", (string)null);
                });

            modelBuilder.Entity("MaxiSchool.Models.Matiere", b =>
                {
                    b.Property<int>("MatiereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MatiereId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MatiereId");

                    b.ToTable("Matieres", (string)null);
                });

            modelBuilder.Entity("MaxiSchool.Models.Professeur", b =>
                {
                    b.Property<int>("ProfesseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProfesseurId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProfesseurId");

                    b.ToTable("Professeurs", (string)null);
                });

            modelBuilder.Entity("MatiereProfesseur", b =>
                {
                    b.HasOne("MaxiSchool.Models.Matiere", null)
                        .WithMany()
                        .HasForeignKey("MatieresMatiereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MaxiSchool.Models.Professeur", null)
                        .WithMany()
                        .HasForeignKey("ProfesseursProfesseurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MaxiSchool.Models.Eleve", b =>
                {
                    b.HasOne("MaxiSchool.Models.Classe", "Classe")
                        .WithMany("Eleves")
                        .HasForeignKey("ClasseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classe");
                });

            modelBuilder.Entity("MaxiSchool.Models.Classe", b =>
                {
                    b.Navigation("Eleves");
                });
#pragma warning restore 612, 618
        }
    }
}
